# Generated by Django 4.2.7 on 2025-06-09 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('2_days', '2 dias antes'), ('1_day', '1 dia antes'), ('same_day', 'No dia')], max_length=20)),
                ('scheduled_for', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date_time']},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='notes',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='reminder_sent',
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendado'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('completed', 'Concluído'), ('no_show', 'Não Compareceu')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
        migrations.AddField(
            model_name='appointmentreminder',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment'),
        ),
        migrations.AlterUniqueTogether(
            name='appointmentreminder',
            unique_together={('appointment', 'reminder_type')},
        ),
    ]
