# Generated by Django 4.2.7 on 2025-06-18 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointmentreminder_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(default='start', max_length=50)),
                ('temp_date', models.DateField(blank=True, null=True)),
                ('temp_time', models.TimeField(blank=True, null=True)),
                ('temp_type', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointments.client')),
            ],
        ),
    ]
