# Generated by Django 4.2.7 on 2025-06-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_conversationstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='source',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('site', 'Site')], default='whatsapp', max_length=20),
        ),
    ]
