# Generated by Django 4.2.7 on 2025-06-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_google_calendar_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentreminder',
            name='reminder_type',
            field=models.CharField(choices=[('2_days', '2 dias antes'), ('1_day', '1 dia antes'), ('1_hour', '1 hora antes'), ('same_day', 'No dia')], max_length=20),
        ),
    ]
