# Generated by Django 4.2.7 on 2025-07-18 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_update_reminder_types'),
        ('appointments', '0007_alter_appointmentreminder_reminder_type'),
    ]

    operations = [
    ]
