# Generated by Django 4.2.7 on 2025-07-18 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_email'),
        ('appointments', '0008_merge_20250717_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReminderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.TextField()),
                ('reminder_timing', models.CharField(max_length=100)),
                ('scheduled_for', models.DateTimeField()),
                ('message', models.TextField()),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.RemoveField(
            model_name='conversationstate',
            name='client',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
        migrations.AddField(
            model_name='appointmentreminder',
            name='custom_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentreminder',
            name='custom_timing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='source',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('site', 'Site'), ('phone', 'Telefone'), ('admin', 'Administrativo')], default='whatsapp', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendada'), ('confirmed', 'Confirmada'), ('completed', 'Concluída'), ('cancelled', 'Cancelada'), ('no_show', 'Não compareceu')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointmentreminder',
            name='reminder_type',
            field=models.CharField(choices=[('1_day', '1 dia antes'), ('2_hours', '2 horas antes'), ('same_day', 'No dia'), ('custom', 'Personalizado')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ConversationState',
        ),
        migrations.AddField(
            model_name='customreminderrequest',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='customreminderrequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
    ]
