version: '3.8'

services:
  # Banco de dados PostgreSQL
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: whatsapp_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - whatsapp_network

  # Redis para Celery
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - whatsapp_network

  # Backend Django
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=whatsapp_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - EVOLUTION_API_URL=https://evo.og-trk.xyz
      - EVOLUTION_API_KEY=067CD1A2E662-483F-A776-C977DED90692
      - EVOLUTION_INSTANCE_ID=pedro
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your-openai-api-key-here}
    volumes:
      - ./whatsapp_backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
      - redis
    networks:
      - whatsapp_network

  # Celery Worker
  celery:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    command: celery -A whatsapp_backend worker -l info
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=whatsapp_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - EVOLUTION_API_URL=https://evo.og-trk.xyz
      - EVOLUTION_API_KEY=067CD1A2E662-483F-A776-C977DED90692
      - EVOLUTION_INSTANCE_ID=pedro
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your-openai-api-key-here}
    volumes:
      - ./whatsapp_backend:/app
    depends_on:
      - db
      - redis
      - backend
    networks:
      - whatsapp_network

  # Celery Beat (agendador)
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    command: celery -A whatsapp_backend beat -l info
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=whatsapp_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./whatsapp_backend:/app
      - celery_beat_data:/app/beat
    depends_on:
      - db
      - redis
      - backend
    networks:
      - whatsapp_network

  # Frontend Angular
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    ports:
      - "9000:80"
    depends_on:
      - backend
    networks:
      - whatsapp_network

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
  celery_beat_data:

networks:
  whatsapp_network:
    driver: bridge 