# Generated by Django 4.2.7 on 2025-06-24 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_id', models.CharField(default='primary', max_length=255)),
                ('appointment_duration', models.IntegerField(default=60)),
                ('buffer_time', models.IntegerField(default=15)),
                ('work_days', models.JSONField(default=list)),
                ('work_hours_start', models.TimeField(default='08:00')),
                ('work_hours_end', models.TimeField(default='18:00')),
                ('lunch_start', models.TimeField(default='12:00')),
                ('lunch_end', models.TimeField(default='14:00')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Google Calendar',
                'verbose_name_plural': 'Configurações Google Calendar',
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_uri', models.URLField(default='https://oauth2.googleapis.com/token')),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('scopes', models.JSONField(default=list)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credencial Google Calendar',
                'verbose_name_plural': 'Credenciais Google Calendar',
            },
        ),
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant_name', models.CharField(default='Elô', max_length=100)),
                ('personality', models.TextField(default='Sou uma assistente calorosa, empática e profissional.')),
                ('clinic_info', models.TextField(default='Clínica especializada em saúde mental e bem-estar.')),
                ('doctor_name', models.CharField(default='Dra. Elisa Munaretti', max_length=100)),
                ('doctor_specialties', models.JSONField(default=list)),
                ('working_hours', models.CharField(default='Segunda a sexta: 8h às 18h', max_length=200)),
                ('appointment_duration', models.IntegerField(default=60)),
                ('response_style', models.CharField(choices=[('formal', 'Formal e profissional'), ('friendly', 'Amigável e caloroso'), ('casual', 'Descontraído e informal'), ('empathetic', 'Empático e acolhedor')], default='empathetic', max_length=50)),
                ('use_emojis', models.BooleanField(default=True)),
                ('auto_scheduling', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração da IA',
                'verbose_name_plural': 'Configurações da IA',
                'unique_together': {('user',)},
            },
        ),
    ]
