# Generated by Django 4.2.7 on 2025-06-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_evolutionconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolutionconfig',
            name='instance_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
