# Generated by Django 4.2.7 on 2025-06-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_alter_evolutionconfig_instance_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evolutionconfig',
            options={'verbose_name': 'Evolution API Configuration', 'verbose_name_plural': 'Evolution API Configurations'},
        ),
        migrations.RemoveField(
            model_name='evolutionconfig',
            name='webhook_token',
        ),
        migrations.AlterField(
            model_name='evolutionconfig',
            name='instance_id',
            field=models.CharField(max_length=255),
        ),
    ]
