# Generated by Django 4.2.7 on 2025-06-10 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_client_alter_user_profile_image'),
        ('whatsapp', '0004_alter_evolutionconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('waiting', 'Aguardando'), ('completed', 'Concluída')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_from_bot', models.BooleanField(default=False)),
                ('intent', models.CharField(blank=True, max_length=50, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
