# Generated by Django 4.2.7 on 2025-06-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_conversation_alter_whatsappmessage_client_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='direction',
            field=models.CharField(choices=[('SENT', 'Enviada'), ('RECEIVED', 'Recebida')], default='RECEIVED', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='message_type',
            field=models.CharField(choices=[('RECEIVED', 'Recebida'), ('SENT', 'Enviada'), ('NOTIFICATION', 'Notificação')], default='RECEIVED', max_length=20),
        ),
    ]
